/**
 * AUTO-GENERATED by `npm run gen:types`
 * Do NOT edit manually. Run `npm run gen:types` after any database migration.
 *
 * Generated from: Supabase project (Singapore region)
 * Last generated: 2026-03-22
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      athletes: {
        Row: {
          id: string
          name: string
          caregiver_user_id: string | null
          photo_url: string | null
          active: boolean
          date_of_birth: string | null
          joined_at: string | null
          running_goal: string | null
          communication_notes: string | null
          medical_notes: string | null
          emergency_contact: string | null
          updated_by: string | null
          updated_at: string | null
          created_at: string | null
          goal_type: string | null
          goal_target: number | null
          allow_public_sharing: boolean
          sharing_disabled_by_caregiver: boolean
          athlete_pin: string | null
          pin_attempts: number
          pin_locked_until: string | null
          theme_color: string | null
          athlete_goal_choice: string | null
          working_on: string | null
          recent_progress: string | null
          working_on_updated_at: string | null
          working_on_updated_by: string | null
          avatar: string | null
          goal_choice_updated_at: string | null
          previous_goal_choice: string | null
          previous_goal_choice_at: string | null
        }
        Insert: {
          id?: string
          name: string
          caregiver_user_id?: string | null
          photo_url?: string | null
          active?: boolean
          date_of_birth?: string | null
          joined_at?: string | null
          running_goal?: string | null
          communication_notes?: string | null
          medical_notes?: string | null
          emergency_contact?: string | null
          updated_by?: string | null
          updated_at?: string | null
          created_at?: string | null
          goal_type?: string | null
          goal_target?: number | null
          allow_public_sharing?: boolean
          sharing_disabled_by_caregiver?: boolean
          athlete_pin?: string | null
          pin_attempts?: number
          pin_locked_until?: string | null
          theme_color?: string | null
          athlete_goal_choice?: string | null
          working_on?: string | null
          recent_progress?: string | null
          working_on_updated_at?: string | null
          working_on_updated_by?: string | null
          avatar?: string | null
          goal_choice_updated_at?: string | null
          previous_goal_choice?: string | null
          previous_goal_choice_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          caregiver_user_id?: string | null
          photo_url?: string | null
          active?: boolean
          date_of_birth?: string | null
          joined_at?: string | null
          running_goal?: string | null
          communication_notes?: string | null
          medical_notes?: string | null
          emergency_contact?: string | null
          updated_by?: string | null
          updated_at?: string | null
          created_at?: string | null
          goal_type?: string | null
          goal_target?: number | null
          allow_public_sharing?: boolean
          sharing_disabled_by_caregiver?: boolean
          athlete_pin?: string | null
          pin_attempts?: number
          pin_locked_until?: string | null
          theme_color?: string | null
          athlete_goal_choice?: string | null
          working_on?: string | null
          recent_progress?: string | null
          working_on_updated_at?: string | null
          working_on_updated_by?: string | null
          avatar?: string | null
          goal_choice_updated_at?: string | null
          previous_goal_choice?: string | null
          previous_goal_choice_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "athletes_caregiver_user_id_fkey"
            columns: ["caregiver_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "athletes_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "athletes_working_on_updated_by_fkey"
            columns: ["working_on_updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      athlete_favorites: {
        Row: {
          id: string
          athlete_id: string
          session_id: string
          created_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          session_id: string
          created_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          session_id?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "athlete_favorites_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "athlete_favorites_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      athlete_messages: {
        Row: {
          id: string
          athlete_id: string
          message: string
          created_at: string
          viewed_by_coach_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          message: string
          created_at?: string
          viewed_by_coach_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          message?: string
          created_at?: string
          viewed_by_coach_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "athlete_messages_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      athlete_moods: {
        Row: {
          id: string
          athlete_id: string
          mood: number
          created_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          mood: number
          created_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          mood?: number
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "athlete_moods_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          id: string
          actor_id: string | null
          actor_email: string | null
          actor_role: string | null
          action: string
          target_type: string | null
          target_id: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id?: string | null
          actor_email?: string | null
          actor_role?: string | null
          action: string
          target_type?: string | null
          target_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string | null
          actor_email?: string | null
          actor_role?: string | null
          action?: string
          target_type?: string | null
          target_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Relationships: []
      }
      cheers: {
        Row: {
          id: string
          athlete_id: string
          user_id: string
          message: string
          viewed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          user_id: string
          message: string
          viewed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          user_id?: string
          message?: string
          viewed_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cheers_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      club_inquiries: {
        Row: {
          id: string
          club_name: string
          contact_name: string
          email: string
          programme_info: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          club_name: string
          contact_name: string
          email: string
          programme_info?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          club_name?: string
          contact_name?: string
          email?: string
          programme_info?: string | null
          status?: string
          created_at?: string
        }
        Relationships: []
      }
      clubs: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          home_location: string | null
          session_day: string | null
          session_time: string | null
          strava_club_id: number | null
          timezone: string
          updated_at: string | null
          slug: string
          tagline: string | null
          strava_hashtag_prefix: string | null
          locale: string
          recurring_session_day: number | null
          recurring_session_time: string | null
          recurring_session_end: string | null
          recurring_session_location: string | null
          recurring_auto_draft: boolean
          max_athletes_per_coach: number
        }
        Insert: {
          id?: string
          name?: string
          logo_url?: string | null
          home_location?: string | null
          session_day?: string | null
          session_time?: string | null
          strava_club_id?: number | null
          timezone?: string
          updated_at?: string | null
          slug?: string
          tagline?: string | null
          strava_hashtag_prefix?: string | null
          locale?: string
          recurring_session_day?: number | null
          recurring_session_time?: string | null
          recurring_session_end?: string | null
          recurring_session_location?: string | null
          recurring_auto_draft?: boolean
          max_athletes_per_coach?: number
        }
        Update: {
          id?: string
          name?: string
          logo_url?: string | null
          home_location?: string | null
          session_day?: string | null
          session_time?: string | null
          strava_club_id?: number | null
          timezone?: string
          updated_at?: string | null
          slug?: string
          tagline?: string | null
          strava_hashtag_prefix?: string | null
          locale?: string
          recurring_session_day?: number | null
          recurring_session_time?: string | null
          recurring_session_end?: string | null
          recurring_session_location?: string | null
          recurring_auto_draft?: boolean
          max_athletes_per_coach?: number
        }
        Relationships: []
      }
      club_settings: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          home_location: string | null
          session_day: string | null
          session_time: string | null
          strava_club_id: number | null
          timezone: string
          updated_at: string | null
          slug: string
          tagline: string | null
          strava_hashtag_prefix: string | null
          locale: string
        }
        Insert: {
          id?: string
          name?: string
          logo_url?: string | null
          home_location?: string | null
          session_day?: string | null
          session_time?: string | null
          strava_club_id?: number | null
          timezone?: string
          updated_at?: string | null
          slug?: string
          tagline?: string | null
          strava_hashtag_prefix?: string | null
          locale?: string
        }
        Update: {
          id?: string
          name?: string
          logo_url?: string | null
          home_location?: string | null
          session_day?: string | null
          session_time?: string | null
          strava_club_id?: number | null
          timezone?: string
          updated_at?: string | null
          slug?: string
          tagline?: string | null
          strava_hashtag_prefix?: string | null
          locale?: string
        }
        Relationships: []
      }
      coach_badges: {
        Row: {
          id: string
          user_id: string
          badge_key: string
          earned_at: string
        }
        Insert: {
          id?: string
          user_id: string
          badge_key: string
          earned_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          badge_key?: string
          earned_at?: string
        }
        Relationships: []
      }
      coach_notes: {
        Row: {
          id: string
          athlete_id: string
          coach_user_id: string | null
          content: string
          note_type: string
          visibility: string
          include_in_story: boolean
          created_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          coach_user_id?: string | null
          content: string
          note_type?: string
          visibility?: string
          include_in_story?: boolean
          created_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          coach_user_id?: string | null
          content?: string
          note_type?: string
          visibility?: string
          include_in_story?: boolean
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "coach_notes_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "coach_notes_coach_user_id_fkey"
            columns: ["coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      cues: {
        Row: {
          id: string
          athlete_id: string
          helps: string[]
          avoid: string[]
          best_cues: string[]
          kit: string[]
          version: number
          previous_cues: Json | null
          updated_by: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          helps?: string[]
          avoid?: string[]
          best_cues?: string[]
          kit?: string[]
          version?: number
          previous_cues?: Json | null
          updated_by?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          helps?: string[]
          avoid?: string[]
          best_cues?: string[]
          kit?: string[]
          version?: number
          previous_cues?: Json | null
          updated_by?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cues_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: true
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cues_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      focus_areas: {
        Row: {
          id: string
          athlete_id: string
          title: string
          progress_note: string | null
          progress_level: string | null
          status: string | null
          created_by: string | null
          created_at: string | null
          achieved_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          title: string
          progress_note?: string | null
          progress_level?: string | null
          status?: string | null
          created_by?: string | null
          created_at?: string | null
          achieved_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          title?: string
          progress_note?: string | null
          progress_level?: string | null
          status?: string | null
          created_by?: string | null
          created_at?: string | null
          achieved_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "focus_areas_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "focus_areas_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          id: string
          email: string
          role: string
          athlete_id: string | null
          invited_by: string | null
          token: string
          expires_at: string
          accepted_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          email: string
          role: string
          athlete_id?: string | null
          invited_by?: string | null
          token?: string
          expires_at?: string
          accepted_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          role?: string
          athlete_id?: string | null
          invited_by?: string | null
          token?: string
          expires_at?: string
          accepted_at?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invitations_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invitations_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      kudos: {
        Row: {
          id: string
          session_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kudos_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          id: string
          athlete_id: string
          session_id: string | null
          milestone_id: string | null
          url: string
          caption: string | null
          uploaded_by: string | null
          source: string | null
          storage_path: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          session_id?: string | null
          milestone_id?: string | null
          url: string
          caption?: string | null
          uploaded_by?: string | null
          source?: string | null
          storage_path?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          session_id?: string | null
          milestone_id?: string | null
          url?: string
          caption?: string | null
          uploaded_by?: string | null
          source?: string | null
          storage_path?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "media_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      milestone_definitions: {
        Row: {
          id: string
          label: string
          type: string
          condition: Json | null
          icon: string | null
          display_order: number
          active: boolean
          created_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          label: string
          type: string
          condition?: Json | null
          icon?: string | null
          display_order?: number
          active?: boolean
          created_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          label?: string
          type?: string
          condition?: Json | null
          icon?: string | null
          display_order?: number
          active?: boolean
          created_by?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "milestone_definitions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      milestones: {
        Row: {
          id: string
          athlete_id: string
          milestone_definition_id: string | null
          label: string
          achieved_at: string
          awarded_by: string | null
          session_id: string | null
          share_image_url: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          milestone_definition_id?: string | null
          label: string
          achieved_at?: string
          awarded_by?: string | null
          session_id?: string | null
          share_image_url?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          milestone_definition_id?: string | null
          label?: string
          achieved_at?: string
          awarded_by?: string | null
          session_id?: string | null
          share_image_url?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "milestones_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_awarded_by_fkey"
            columns: ["awarded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_milestone_definition_id_fkey"
            columns: ["milestone_definition_id"]
            isOneToOne: false
            referencedRelation: "milestone_definitions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json
          read: boolean
          channel: string
          delivered_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json
          read?: boolean
          channel?: string
          delivered_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          payload?: Json
          read?: boolean
          channel?: string
          delivered_at?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          endpoint?: string
          p256dh?: string
          auth?: string
          created_at?: string | null
        }
        Relationships: []
      }
      session_rsvp: {
        Row: {
          id: string
          session_id: string
          user_id: string
          status: string
          note: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          status: string
          note?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          status?: string
          note?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "session_rsvp_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_rsvp_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sessions: {
        Row: {
          id: string
          athlete_id: string
          coach_user_id: string | null
          planned_coach_user_id: string | null
          strava_activity_id: number | null
          status: string
          date: string
          distance_km: number | null
          duration_seconds: number | null
          feel: number | null
          note: string | null
          route_name: string | null
          map_polyline: string | null
          weather: string | null
          sync_source: string | null
          match_method: string | null
          match_confidence: string | null
          strava_deleted_at: string | null
          strava_title: string | null
          avg_heart_rate: number | null
          max_heart_rate: number | null
          created_at: string | null
          training_session_id: string | null
        }
        Insert: {
          id?: string
          athlete_id: string
          coach_user_id?: string | null
          planned_coach_user_id?: string | null
          strava_activity_id?: number | null
          status?: string
          date: string
          distance_km?: number | null
          duration_seconds?: number | null
          feel?: number | null
          note?: string | null
          route_name?: string | null
          map_polyline?: string | null
          weather?: string | null
          sync_source?: string | null
          match_method?: string | null
          match_confidence?: string | null
          strava_deleted_at?: string | null
          strava_title?: string | null
          avg_heart_rate?: number | null
          max_heart_rate?: number | null
          created_at?: string | null
          training_session_id?: string | null
        }
        Update: {
          id?: string
          athlete_id?: string
          coach_user_id?: string | null
          planned_coach_user_id?: string | null
          strava_activity_id?: number | null
          status?: string
          date?: string
          distance_km?: number | null
          duration_seconds?: number | null
          feel?: number | null
          note?: string | null
          route_name?: string | null
          map_polyline?: string | null
          weather?: string | null
          sync_source?: string | null
          match_method?: string | null
          match_confidence?: string | null
          strava_deleted_at?: string | null
          strava_title?: string | null
          avg_heart_rate?: number | null
          max_heart_rate?: number | null
          created_at?: string | null
          training_session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sessions_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sessions_coach_user_id_fkey"
            columns: ["coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sessions_planned_coach_user_id_fkey"
            columns: ["planned_coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      story_updates: {
        Row: {
          id: string
          athlete_id: string
          coach_user_id: string | null
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          athlete_id: string
          coach_user_id?: string | null
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          athlete_id?: string
          coach_user_id?: string | null
          content?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "story_updates_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "story_updates_coach_user_id_fkey"
            columns: ["coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      strava_connections: {
        Row: {
          user_id: string
          strava_athlete_id: number
          access_token: string
          refresh_token: string
          token_expires_at: string
          last_sync_at: string | null
          last_sync_status: string | null
          last_error: string | null
          created_at: string | null
        }
        Insert: {
          user_id: string
          strava_athlete_id: number
          access_token: string
          refresh_token: string
          token_expires_at: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          last_error?: string | null
          created_at?: string | null
        }
        Update: {
          user_id?: string
          strava_athlete_id?: number
          access_token?: string
          refresh_token?: string
          token_expires_at?: string
          last_sync_at?: string | null
          last_sync_status?: string | null
          last_error?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "strava_connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      strava_sync_log: {
        Row: {
          id: string
          strava_activity_id: number
          coach_user_id: string | null
          event_type: string
          event_time: string | null
          received_at: string
          processed_at: string | null
          status: string
          result_session_id: string | null
          error_message: string | null
          raw_payload: Json
        }
        Insert: {
          id?: string
          strava_activity_id: number
          coach_user_id?: string | null
          event_type: string
          event_time?: string | null
          received_at?: string
          processed_at?: string | null
          status?: string
          result_session_id?: string | null
          error_message?: string | null
          raw_payload: Json
        }
        Update: {
          id?: string
          strava_activity_id?: number
          coach_user_id?: string | null
          event_type?: string
          event_time?: string | null
          received_at?: string
          processed_at?: string | null
          status?: string
          result_session_id?: string | null
          error_message?: string | null
          raw_payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: "strava_sync_log_coach_user_id_fkey"
            columns: ["coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "strava_sync_log_result_session_id_fkey"
            columns: ["result_session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      strava_unmatched: {
        Row: {
          id: string
          coach_user_id: string | null
          strava_activity_id: number
          activity_data: Json
          resolution_type: string | null
          created_at: string | null
          resolved_at: string | null
          resolved_by: string | null
          resolved_session_id: string | null
        }
        Insert: {
          id?: string
          coach_user_id?: string | null
          strava_activity_id: number
          activity_data: Json
          resolution_type?: string | null
          created_at?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          resolved_session_id?: string | null
        }
        Update: {
          id?: string
          coach_user_id?: string | null
          strava_activity_id?: number
          activity_data?: Json
          resolution_type?: string | null
          created_at?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          resolved_session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "strava_unmatched_coach_user_id_fkey"
            columns: ["coach_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "strava_unmatched_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "strava_unmatched_resolved_session_id_fkey"
            columns: ["resolved_session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      training_sessions: {
        Row: {
          id: string
          club_id: string
          title: string | null
          session_start: string
          session_end: string | null
          location: string
          notes: string | null
          status: string
          coach_rsvp_deadline: string | null
          athlete_rsvp_deadline: string | null
          pairings_published_at: string | null
          pairings_stale: boolean
          completed_at: string | null
          created_by: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          club_id: string
          title?: string | null
          session_start: string
          session_end?: string | null
          location: string
          notes?: string | null
          status?: string
          coach_rsvp_deadline?: string | null
          athlete_rsvp_deadline?: string | null
          pairings_published_at?: string | null
          pairings_stale?: boolean
          completed_at?: string | null
          created_by: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          club_id?: string
          title?: string | null
          session_start?: string
          session_end?: string | null
          location?: string
          notes?: string | null
          status?: string
          coach_rsvp_deadline?: string | null
          athlete_rsvp_deadline?: string | null
          pairings_published_at?: string | null
          pairings_stale?: boolean
          completed_at?: string | null
          created_by?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "training_sessions_club_id_fkey"
            columns: ["club_id"]
            isOneToOne: false
            referencedRelation: "clubs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "training_sessions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      session_coach_rsvps: {
        Row: {
          id: string
          session_id: string
          coach_id: string
          status: string
          responded_at: string | null
          responded_by: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          coach_id: string
          status?: string
          responded_at?: string | null
          responded_by?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          coach_id?: string
          status?: string
          responded_at?: string | null
          responded_by?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "session_coach_rsvps_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "training_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_coach_rsvps_coach_id_fkey"
            columns: ["coach_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_coach_rsvps_responded_by_fkey"
            columns: ["responded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      session_athlete_rsvps: {
        Row: {
          id: string
          session_id: string
          athlete_id: string
          status: string
          responded_by: string | null
          responded_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          athlete_id: string
          status?: string
          responded_by?: string | null
          responded_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          athlete_id?: string
          status?: string
          responded_by?: string | null
          responded_at?: string | null
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "session_athlete_rsvps_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "training_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_athlete_rsvps_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_athlete_rsvps_responded_by_fkey"
            columns: ["responded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      session_assignments: {
        Row: {
          id: string
          session_id: string
          coach_id: string
          athlete_id: string
          created_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          coach_id: string
          athlete_id: string
          created_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          coach_id?: string
          athlete_id?: string
          created_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "session_assignments_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "training_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_assignments_coach_id_fkey"
            columns: ["coach_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_assignments_athlete_id_fkey"
            columns: ["athlete_id"]
            isOneToOne: false
            referencedRelation: "athletes"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          role: string
          active: boolean
          created_at: string | null
          pwa_token: string | null
          pwa_token_expires_at: string | null
          can_manage_sessions: boolean
          session_notifications: boolean
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          role?: string
          active?: boolean
          created_at?: string | null
          pwa_token?: string | null
          pwa_token_expires_at?: string | null
          can_manage_sessions?: boolean
          session_notifications?: boolean
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          role?: string
          active?: boolean
          created_at?: string | null
          pwa_token?: string | null
          pwa_token_expires_at?: string | null
          can_manage_sessions?: boolean
          session_notifications?: boolean
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_my_role: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      get_total_km: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      get_weekly_stats: {
        Args: {
          since: string
        }
        Returns: {
          session_count: number
          total_km: number
          athlete_count: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
        PublicSchema["Views"])
    ? (PublicSchema["Tables"] &
        PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
    ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
    ? PublicSchema["Enums"][PublicEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof PublicSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof PublicSchema["CompositeTypes"]
    ? PublicSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never
